# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dental_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(170, 40, 211, 141))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(70, 60, 81, 16))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 40, 221, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(80, 60, 81, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 330, 221, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(70, 60, 91, 20))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 180, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 180, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 470, 121, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(300, 330, 221, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(80, 60, 61, 20))
        self.label_5.setObjectName("label_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(579, 330, 221, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(70, 60, 91, 20))
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 470, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(640, 470, 111, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YeniTıp Diş Çürüğü Tespit Sistemi"))
        self.groupBox.setTitle(_translate("MainWindow", "Röntgen Görüntüsü"))
        self.label.setText(_translate("MainWindow", "XRayLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Mask Görüntüsü"))
        self.label_2.setText(_translate("MainWindow", "MaskLabel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Fizik Tabanlı Sonuç"))
        self.label_4.setText(_translate("MainWindow", "resultsPhysics"))
        self.pushButton.setText(_translate("MainWindow", "Röntgen Yükle"))
        self.pushButton_2.setText(_translate("MainWindow", "Mask Yükle"))
        self.pushButton_3.setText(_translate("MainWindow", "Fizik Analiz"))
        self.groupBox_4.setTitle(_translate("MainWindow", "ML Tabanlı Sonuç"))
        self.label_5.setText(_translate("MainWindow", "resultsML"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Fizik - ML Hibrit Sonuç"))
        self.label_6.setText(_translate("MainWindow", "resultsHybrid"))
        self.pushButton_4.setText(_translate("MainWindow", "ML Analiz"))
        self.pushButton_5.setText(_translate("MainWindow", "Hibrit Analiz"))
